### PR TITLE
Add pq based config variables to pictl, remove python from pictl

### PR DESCRIPTION
**Pull request by TokinRing**
I'm adding the part for parsing values from the config.json into variables usable in the pictl bash script. I've also changed `/bin/bash` to `/usr/bin/env bash` to make the script more portable.

I also noticed that a section was created to use python. Do we really need to add in another language for one or two minor functions? I'm all for python, but lets try not to turn PiCluster into a multi-language hydra.

### CODE REVIEW

**Comment by aidanharris** [comment]
@TokinRing It's (python) used to pretty print the JSON and done in a portable way. We have several options here:

1) Parse the JSON using jq (this would add a dependency on jq) - This would be my preferred vote
2) Parse the JSON using a homegrown script (sed/awk) - Ugly but effective and avoids third-party dependencies
3) Pretty print the JSON using a combination of the above
4) Do nothing - Just print the output (this is what the backwards compatible python function does)

We should probably create a proper issue to track this.

**Comment by aidanharris** [comment]
@TokinRing Looks like shellcheck has some suggestions for you:

https://travis-ci.org/picluster/picluster/builds/265442863#L2362

**Comment by TokinRing** [comment]
I'll have a look at this sometime tomorrow. I'll probably also have to add jq to the travis config.

**Comment by aidanharris** [comment]
jq is already in travis so there's no need to worry about that.

**Pull request closed without merging**
